# Generated by Django 4.2.1 on 2023-05-14 10:54

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name=myapp.models.UnverifiedData)),
            ],
        ),
        migrations.CreateModel(
            name='UnverifiedData',
            fields=[
                ('s_no', models.IntegerField(default=1)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=70)),
                ('pin', models.CharField(max_length=16)),
                ('country', models.CharField(default='India', max_length=70)),
                ('state', models.CharField(max_length=70)),
                ('landline_no', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=180)),
                ('email_id', models.CharField(max_length=254)),
                ('website', models.CharField(db_collation='utf8mb4_bin', max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MXRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateField()),
                ('last_seen', models.DateField()),
                ('organizations', models.TextField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mx_records', to='myapp.domain')),
            ],
        ),
        migrations.CreateModel(
            name='MailServerHistorical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('mx_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_servers', to='myapp.mxrecord')),
            ],
        ),
        migrations.CreateModel(
            name='MailServercurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_host', models.CharField(max_length=255)),
                ('current_mx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_mail_servers', to='myapp.mxrecord')),
            ],
        ),
    ]
