# Generated by Django 4.2.1 on 2023-05-14 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MXRecordcurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateField()),
                ('last_seen', models.DateField()),
                ('organizations', models.TextField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mx_records_current', to='myapp.domain')),
            ],
        ),
        migrations.AlterField(
            model_name='mailservercurrent',
            name='current_mx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_mail_servers', to='myapp.mxrecordcurrent'),
        ),
    ]
