# Generated by Django 4.2.1 on 2023-05-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mxrecordcurrent_alter_mailservercurrent_current_mx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MXRecord',
            new_name='MXRecordAll',
        ),
    ]
