# Generated by Django 4.2.1 on 2023-05-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_country_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='mxrecordall',
            name='country',
            field=models.CharField(default='India', max_length=70),
        ),
        migrations.AddField(
            model_name='mxrecordall',
            name='state',
            field=models.CharField(default='Delhi', max_length=70),
        ),
        migrations.AddField(
            model_name='mxrecordcurrent',
            name='country',
            field=models.CharField(default='India', max_length=70),
        ),
        migrations.AddField(
            model_name='mxrecordcurrent',
            name='state',
            field=models.CharField(default='Delhi', max_length=70),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
