# Generated by Django 4.2.1 on 2024-02-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_mxrecordall_selected_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifieddata',
            name='s_no',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AddIndex(
            model_name='mxrecordcurrent',
            index=models.Index(fields=['selected_month', 'country', 'state'], name='myapp_mxrec_selecte_7f5105_idx'),
        ),
    ]
